{"name": "Проверка ответа на запрос изменения данных неаутентифицированного пользователя", "status": "passed", "start": 1747679241446, "stop": 1747679241731, "uuid": "abb15add-276c-4f50-94f0-d69bb04bd502", "historyId": "15ddd7987c2e5999e579e59a038213af", "testCaseId": "15ddd7987c2e5999e579e59a038213af", "fullName": "tests.test_user_update.TestUserUpdate#test_update_user_unauthenticated_expected_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_update"}, {"name": "subSuite", "value": "TestUserUpdate"}, {"name": "host", "value": "cat"}, {"name": "thread", "value": "12084-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_update"}]}